[build]
  command = "npm run build"
  publish = "out"
  timeout = 1200 # Increase the timeout to 20 minutes

[build.environment]
  DATABASE_URL = "postgresql://postgres.efdtrpwmciaohploynjo:HypbY1h4LlpKw1tf@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres"

[[plugins]]
  package = "@netlify/plugin-nextjs"
